import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF0F6AD7);
const kTextColor = Colors.black;
const kTextColorHint = Color(0xFF797979);
const kBackgroundColor = Color(0xFFF3F5F7);

const kColorBySubject = {
  'ART': 0xffFFCF87,
  'HIST': 0xffee9c42,
  'ENVS': 0xffccee42,
  'LACS': 0xffc93846,
  'LARA': 0xff3aae9d,
  'LLIT': 0xff052d3d,
  'GPS': 0xff5E9663,
  'MLSC': 0xff765130,
  'ACCT': 0xff82BBFF,
  'EDUC': 0xff8F372C,
  'LANG': 0xff9C511B,
  'LFRE': 0xff3A4146,
  'CHEM': 0xff5E778D,
  'COMM': 0xff36B39C,
  'GNSC': 0xffBF7665,
  'CAIS': 0xffB72F2F,
  'FINC': 0xffFF9671,
  'GEOL': 0xff845EC2,
  'LSPA': 0xff00C9A7,
  'MUSC': 0xff845EC2,
  'ECON': 0xffB0A8B9,
  'EGST': 0xff0081CF,
  'POLS': 0xff00C9A7,
  'SOCI': 0xffC34A36,
  'MGMT': 0xff4B4453,
  'CRJU': 0xff34839C,
  'IDIS': 0xff00C2A8,
  'PSYC': 0xff9B89B3,
  'MRKT': 0xff936C00,
  'MATH': 0xff00D2FC,
  'Lab': 0xff009EFA,
  'HESC': 0xff4FFBDF,
  'NURS': 0xffB15B00,
  'PHSC': 0xff3596B5,
  'LASL': 0xff845EC2,
  'ASTR': 0xffD5CABD,
  'ENGL': 0xffFF8066,
  'SOCW': 0xffD03B29,
  'THEA': 0xffC197FF,
  'MOVP': 0xff00C9A7,
  'BIOL': 0xff005B44,
  'PHIL': 0xff00C9A7,
  'ANTH': 0xff78D781,
};

const kImageBySubject = {
  'ART': 'assets/images/ART.png',
  'HIST': 'assets/images/HIST.png',
  'ENVS': 'assets/images/ENVS.png',
  'LACS': 'assets/images/BOOK.png',
  'LARA': 'assets/images/LARA.png',
  'GPS': 'assets/images/GEOL.png',
  'MLSC': 'assets/images/MLSC.png',
  'ACCT': 'assets/images/ACCT.png',
  'EDUC': 'assets/images/EDUC.png',
  'LANG': 'assets/images/LANG.png',
  'LFRE': 'assets/images/LFRE.png',
  'CHEM': 'assets/images/CHEM.png',
  'COMM': 'assets/images/COMM.png',
  'GNSC': 'assets/images/GNSC.png',
  'CAIS': 'assets/images/CAIS.png',
  'FINC': 'assets/images/FINC.png',
  'GEOL': 'assets/images/GEOL.png',
  'LSPA': 'assets/images/LSPA.png',
  'MUSC': 'assets/images/MUSC.png',
  'ECON': 'assets/images/ECON.png',
  'EGST': 'assets/images/EGST.png',
  'POLS': 'assets/images/BOOK.png',
  'SOCI': 'assets/images/SOCI.png',
  'MGMT': 'assets/images/MGMT.png',
  'CRJU': 'assets/images/CRJU.png',
  'IDIS': 'assets/images/BOOK.png',
  'PSYC': 'assets/images/BOOK.png',
  'MRKT': 'assets/images/MRKT.png',
  'MATH': 'assets/images/MATH.png',
  'Lab': 'assets/images/CHEM.png',
  'HESC': 'assets/images/HESC.png',
  'NURS': 'assets/images/NURS.png',
  'PHSC': 'assets/images/PHSC.png',
  'LASL': 'assets/images/LASL.png',
  'ASTR': 'assets/images/ASTR.png',
  'ENGL': 'assets/images/ENGL.png',
  'SOCW': 'assets/images/SOCW.png',
  'THEA': 'assets/images/THEA.png',
  'MOVP': 'assets/images/MOVP.png',
  'BIOL': 'assets/images/BIOL.png',
  'PHIL': 'assets/images/PHIL.png',
  'ANTH': 'assets/images/BOOK.png',
};

const kSubjectByAlias = {
  'ACCT': 'Accounting',
  'ART': 'Art',
  'ASTR': 'Astronomy',
  'ANTH': 'Anthropology',
  'BIOL': 'Biology',
  'CAIS': 'Computer',
  'CHEM': 'Chemistry',
  'COMM': 'Communication',
  'CRJU': 'Criminal.J',
  'ECON': 'Economics',
  'EDUC': 'Education',
  'EGST': 'Ethnic & Gender',
  'ENGL': 'English',
  'ENVS': 'Environmental',
  'FINC': 'Finance',
  'GARP': 'Geography',
  'GEOL': 'Geology',
  'GERO': 'Gerontology',
  'GNSC': 'Physical',
  'HESC': 'Health',
  'HIST': 'History',
  'IDIS': 'Snr-HNRS.Project',
  'LANG': 'Language',
  'LARA': 'Arabic',
  'LASL': 'Sign Language',
  'LCHI': 'Chinese',
  'LCUL': 'Culture',
  'LFRE': 'French',
  'LLIT': 'Literature',
  'LSPA': 'Spanish',
  'MATH': 'Mathematics',
  'MGMT': 'Management',
  'MLSC': 'Military',
  'MOVP': 'Movement',
  'MRKT': 'Marketing',
  'MUSC': 'Music',
  'NURS': 'Nursing',
  'PHIL': 'Philosophy',
  'PHSC': 'Physics',
  'PSYC': 'Psychology',
  'SOCI': 'Sociology',
  'SOCW': 'Social',
  'THEA': 'Theatre',
};

const kImgByFeatureName = {
  'auto scheduler' : 'assets/images/auto_scheduler.png',
  'prof. rating' : 'assets/images/prof_rating.png',
  'donate' : 'assets/images/donate.png',
};